build:
    environment:
        php: '5.6'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=my-coverage-file'
                coverage:
                    file: 'my-coverage-file'
                    format: 'php-clover'

filter:
    excluded_paths:
        - Tests/*
        - vendor/*

checks:
    php:
      code_rating: true
      duplication: true

tools:
    php_sim: true
    php_changetracking: true
    php_cs_fixer:
        config: { level: psr2 }
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    php_code_coverage: true
    sensiolabs_security_checker: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
