language: php
sudo: false

php:
  - 5.6
  - 7.0

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

matrix:
  fast_finish: true

notifications:
  email: false

before_install:
  - composer config -g github-oauth.github.com $CI_USER_TOKEN

install:
  - composer install --no-progress --prefer-dist

script:
  - phpunit -c phpunit.xml.dist
